/**
 * @file Automatically generated by barrelsby.
 */

export * from "./v2/HelloWorldController";
export * from "./v1/CrudController";
export * from "./v1/ProductController";
export * from "./v1/AxiosController";
